apiRules:
- include:
    # Including the OmiyaGames.Template namespace
    uidRegex: ^OmiyaGames\.Web$
    type: Namespace
- include:
    # Including the OmiyaGames.Template.Editor namespace
    uidRegex: ^OmiyaGames\.Web\.Editor$
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    # Taro Omiya: note that I'm ignoring namespaces containing unit tests on purpooses
    uidRegex: .*
    type: Namespace